### ISSUE TITLE
想了解下这个和TTL的异同点

### ISSUE THREAD

**Issue by JasonMing** [Nepxion/DiscoveryAgent#4]
我见之前alibaba也有一个类似功能的库：https://github.com/alibaba/transmittable-thread-local 
这两个主要差异点可以解答下吗（仅限当前项目，不是整个nepxion平台）？

**Comment by zifeihan** [comment]
不好意思，最近太忙了。
请参考下这个链接，主要就是用来跨线程传递指定的信息使用（通过插件指定哪些信息需要跨线程传递）。 https://blog.csdn.net/weixin_33910305/article/details/115788125
