### ISSUE TITLE
ThreadLocalHook注册bug

### ISSUE THREAD

**Issue by yanbw** [Nepxion/DiscoveryAgent#5]
ThreadPlugin中调用了所有ThreadLocalHook接口(需注册)中的create、before等方法, ThreadLocalHook的注册是在插件(比如DiscoveryServicePlugin)匹配到并执行对应的TransformCallback的doInTransform方法.
当项目启动时发起的第一个灰度请求是异步时
 
![image](https://user-images.githubusercontent.com/12623976/141478794-3b59d11a-8de7-4dbf-91cb-de8f13a0be7f.png)

  
![image](https://user-images.githubusercontent.com/12623976/141477491-6ce6da1f-531c-43ff-b758-a05133a226f2.png)
此时Task构造器先被增强,然而因为Task构造时RestStrategyContext尚未加载, 所以DiscoveryServicePlugin对应的ThreadLocalHook还未注册,Object[] objects = ThreadLocalCopier.create(), 此行代码objects结果为空, 灰度结果会异常.
然后随着灰度代码的执行, 会加载到RestStrategyContext, 然后会执行DiscoveryServicePlugin的TransformCallback的doInTransform方法, 对应的ThreadLocalHook将被注册.
下次异步调用时灰度结果正常.

**Comment by zifeihan** [comment]
> 此时Task构造器先被增强,然而因为Task构造时RestStrategyContext尚未加载, 所以DiscoveryServicePlugin对应的ThreadLocalHook还未注册,Object[] objects = ThreadLocalCopier.create(), 此行代码objects结果为空, 灰度结果会异常.

即使这里为空的话，为什么灰度结果会异常呢？

**Comment by HaojunRen** [comment]
@yanbw 无法重现你说的问题，该测试用例集成在DiscoveryGuide上，经过测试，该问题似乎不存在，你是否可以通过DiscoveryGuide来重新你说的问题？参考https://github.com/Nepxion/DiscoveryGuide/blob/6.x.x/discovery-guide-service/src/main/java/com/nepxion/discovery/guide/service/feign/AFeignImpl.java中
```java
    @Override
    @SentinelResource(value = "sentinel-resource", blockHandler = "handleBlock", fallback = "handleFallback")
    public String invokeThread(@PathVariable(value = "value") String value) {
        Runnable runnable = createRunnable(value);

        new Thread(runnable).start();

        return "Invoke Thread";
    }
```

**Comment by yanbw** [comment]
@HaojunRen @zifeihan 
测试代码如下
![image](https://user-images.githubusercontent.com/12623976/154427008-c9069379-e71d-46da-adc2-faa58f33ccae.png)
启动a、b 1.0版本应用
![image](https://user-images.githubusercontent.com/12623976/154427154-059a3690-6ff2-4458-8234-50edef05bfe3.png)
应用启动后第一次调用(n-d-version = {"discovery-guide-service-b":1.1} )
![image](https://user-images.githubusercontent.com/12623976/154427569-73a4899b-e91a-4905-8369-18692f200d71.png)
调用结果
![image](https://user-images.githubusercontent.com/12623976/154427678-7adc242d-c3a2-4193-a00a-6b06dbca97f6.png)
第二次调用
![image](https://user-images.githubusercontent.com/12623976/154427870-cea3b382-1c03-4bfa-8257-8a0d3e21c172.png)
第二次调用结果,调不通(b应用1.1不存在,调不通才是正常结果)
![image](https://user-images.githubusercontent.com/12623976/154428009-ea46ac13-9212-4e90-88ec-d6957da00713.png)

**Comment by HaojunRen** [comment]
这个问题的确存在。原因是异步的时候， 初始化Agent相关类和业务调用基本同时开始。当业务调用先于Agent初始化完成，那么灰度不会生效。这种情况只会发生在第一次。我们考虑一下，怎么解决

**Comment by HaojunRen** [comment]
一个非技术角度的观点@yanbw

你的异步调用结果只是打印一句话，而真正生产环境的执行代码相对耗时较长，应该绝大多数情况是Agent初始化代码先执行完毕

**Comment by HaojunRen** [comment]
你是否在nepxion群里，请@我一下，或者加我微信1394997

**Comment by HaojunRen** [comment]
已发布Agent 1.2.0，解决了该问题
