### ISSUE TITLE
Collections.emptyList()使用不当问题

### ISSUE THREAD

**Issue by LiZhouYan** [Nepxion/DiscoveryAgent#6]
代码地址：com/nepxion/discovery/agent/plugin/thread/ThreadPlugin.java:55 会出现问题
![image](https://user-images.githubusercontent.com/37104446/153382096-90d429ef-9cb9-4758-bc69-4f85acd0cf81.png)

`List<String> basePackages = StringUtil.tokenizeToStringList(baseThreadScanPackages, ThreadConstant.THREAD_SCAN_PACKAGES_DELIMITERS);
        List<String> customPackages = StringUtil.tokenizeToStringList(threadScanPackages, ThreadConstant.THREAD_SCAN_PACKAGES_DELIMITERS);
        basePackages.addAll(customPackages);`
若是basePackages为emptyList，则后面的不能再用emptyList添加东西了 basePackages.addAll(customPackages);
![image](https://user-images.githubusercontent.com/37104446/153381807-7ea34383-12cb-4366-b5f3-22768aec032b.png)
这行可能是一个失误吧，建议删除这行代码。

**Comment by HaojunRen** [comment]
已发布Agent 1.2.0，解决了该问题
